#ifndef ROBOTPROPIN_H
#define ROBOTPROPIN_H


#define PIN1_MOT_ANT_DX PB8
#define PIN2_MOT_ANT_DX PB9

#define PIN1_MOT_POS_DX PB6
#define PIN2_MOT_POS_DX PB7

#define PIN1_MOT_POS_SX PA8
#define PIN2_MOT_POS_SX PA10

#define PIN1_MOT_ANT_SX PA1
#define PIN2_MOT_ANT_SX PA0


#endif // ROBOTPROPIN_H