; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = blackpill_f411ce

[common]

build_src_filter =  
; +<main.cpp> +<my_lib/> -<test/>

;per eseguire un test commentare la riga sopra e 
;decommentare la riga corrispondente, lasciare almeno uno spazio

;    -<main.cpp> +<my_lib/> +<test/test_al_volo.cpp>
;    -<main.cpp> +<my_lib/> +<test/misura_durata_funzioni.cpp>
;	-<main.cpp> +<my_lib/> +<test/test_bussola_LOG_angoli.cpp>
	
;    -<main.cpp> +<my_lib/> +<test/test_media_mobile.cpp>

;     -<main.cpp> +<my_lib/> +<test/test_bussola_calibrazione.cpp>	
;	-<main.cpp> +<my_lib/> +<test/test_bussola.cpp>
;	-<main.cpp> +<my_lib/> +<test/test_bussola_raw.cpp>

;    -<main.cpp> +<my_lib/> +<test/test_controller_logga_impulsi.cpp>
;     -<main.cpp> +<my_lib/> +<test/test_controller_stampa_RPM.cpp>

;	 -<main.cpp> +<my_lib/> +<test/test_controller_logga_RPM_no_pid.cpp>
;    -<main.cpp> +<my_lib/> +<test/test_oled_controller.cpp>
	 -<main.cpp> +<my_lib/> +<test/test_controller_dritto_a_0_gradi.cpp>
;    -<main.cpp> +<my_lib/> +<test/test_controller_RPM_e_PID.cpp>
;	 -<main.cpp> +<my_lib/> +<test/test_controller_motori.cpp>
;    -<main.cpp> +<my_lib/> +<test/robot_mappa_motori.cpp>
;    -<main.cpp> +<my_lib/> +<test/Robot_test_raw_QuickPID_mot_PS.cpp>
;    -<main.cpp> +<my_lib/> +<test/robot_RPM_Timer_stampa_rpm_di_4_motori.cpp
;    -<main.cpp> +<my_lib/> +<test/robot_motori_conta_RPM_oled_serial.cpp>
;    -<main.cpp> +<my_lib/> +<test/mot_AS_misura_RPM.cpp>
;    -<main.cpp> +<my_lib/> +<test/mot_AS__conta_RPM_min_e_max.cpp>
;    -<main.cpp> +<my_lib/> +<test/motore_AD_encoder_grezzo_contaimpulsi.cpp>
;    -<main.cpp> +<my_lib/> +<test/
;    -<main.cpp> +<my_lib/> +<test/test_robot_controller.cpp>
;    -<main.cpp> +<my_lib/> +<test/robot_oled.cpp>

;no_pid !!!
;    -<main.cpp> +<my_lib/> +<test/robot_mappa_motori.cpp>  ;NO_PID !!!!!!!
;no pid !!!

;    -<main.cpp> +<my_lib/> +<test/robot_RPM_Timer_stampa_rpm_di_4_motori.cpp
;    -<main.cpp> +<my_lib/> +<test/robot_motori_conta_RPM_oled_serial.cpp>
;    -<main.cpp> +<my_lib/> +<test/mot_AS_misura_RPM.cpp>
;    -<main.cpp> +<my_lib/> +<test/mot_AS__conta_RPM_min_e_max.cpp>
;    -<main.cpp> +<my_lib/> +<test/motore_AD_encoder_grezzo_contaimpulsi.cpp>
;    -<main.cpp> +<my_lib/> +<test/test_al_volo.cpp>
;    -<main.cpp> +<my_lib/> +<test/encoder_grezzo.cpp>
;    -<main.cpp> +<my_lib/> +<test/encoder_n20_RPM.cpp>
;    -<main.cpp> +<my_lib/> +<test/blink13.cpp>
;    -<main.cpp> +<my_lib/> +<test/blink13_ACCESO.cpp>
;    -<main.cpp> +<my_lib/> +<test/serial_hw.cpp>
;    -<main.cpp> +<my_lib/> +<test/serial_hw_e_robot.cpp>
;    -<main.cpp> +<my_lib/> +<test/oled_hw.cpp>
;    -<main.cpp> +<my_lib/> +<test/scanI2C.cpp>
;    -<main.cpp> +<my_lib/> +<test/mot_AD_orario.cpp>
;    -<main.cpp> +<my_lib/> +<test/mot_AD_antiorario.cpp>
;    -<main.cpp> +<my_lib/> +<test/mot_PD_orario.cpp>
;    -<main.cpp> +<my_lib/> +<test/mot_PD_antiorario.cpp>
;    -<main.cpp> +<my_lib/> +<test/mot_PS_orario.cpp>
;    -<main.cpp> +<my_lib/> +<test/mot_PS_antiorario.cpp>
;    -<main.cpp> +<my_lib/> +<test/mot_AS_orario.cpp>
;    -<main.cpp> +<my_lib/> +<test/mot_AS_antiorario.cpp>
;    -<main.cpp> +<my_lib/> +<test/mot_TUTTI_orario.cpp>
;    -<main.cpp> +<my_lib/> +<test/mot_TUTTI_avanti_indietro.cpp>
;    -<main.cpp> +<my_lib/> +<test/test_pulsante_on_off.cpp>
;    -<main.cpp> +<my_lib/> +<test/test_pulsante_counter_BAD.cpp>
;    -<main.cpp> +<my_lib/> +<test/test_pulsante_debounce_SW.cpp>
;    -<main.cpp> +<my_lib/> +<test/test_interrupt.cpp>
;    -<main.cpp> +<my_lib/> +<test/enc_AD_raw.cpp>

lib_deps = adafruit/Adafruit SSD1306@^2.5.16
build_flags = 
	-D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
	-D HAS_OLED_DISPLAY
monitor_speed = 115200

[env:blackpill_f411ce]
platform = ststm32
board = blackpill_f411ce
framework = arduino
upload_protocol = stlink
lib_deps = 
	${common.lib_deps}
	dlloydev/QuickPID@^3.1.9
	adafruit/Adafruit QMC5883P Library@^1.0.1
monitor_speed = ${common.monitor_speed}
build_src_filter = ${common.build_src_filter}
build_flags = 
	${common.build_flags}
	;-D BLACKPILL_F411CE_DRV8833
	-D BLACKPILL_F411CE_TB6612FNG
	-D DIMENSIONE_LOG=300
	;-D LOGGA_RPM
	;-D LOGGA_IMPULSI
	;-D LOGGA_BUSSOLA
	
	;-D NO_PID


[env:arduino_mega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
lib_deps = 
	${common.lib_deps}
	dlloydev/QuickPID@^3.1.9
	adafruit/Adafruit QMC5883P Library@^1.0.1
monitor_speed = ${common.monitor_speed}
build_src_filter = ${common.build_src_filter}
build_flags = 
	${common.build_flags}
	-D ARDUINO_MEGA2560
	-D NO_PID


[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
lib_deps = 
	${common.lib_deps}
	dlloydev/QuickPID@^3.1.9
	adafruit/Adafruit QMC5883P Library@^1.0.1
build_src_filter = ${common.build_src_filter}
build_flags = 
	${common.build_flags}
	-D ARDUINO_UNO
