; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[platformio]
default_envs = arduino_mega2560

[common]
;build_src_filter = -<main.cpp> +<test/serial_hw.cpp>
build_src_filter = -<main.cpp> +<test/serial_hw_e_robot.cpp>

;build_src_filter = -<main.cpp> +<test/blink13.cpp>
;build_src_filter = -<main.cpp> +<test/oled_hw.cpp>
;build_src_filter = -<main.cpp> +<test/scanI2C.cpp>
;build_src_filter = -<main.cpp> +<test/mot_AD_orario.cpp>
;build_src_filter = -<main.cpp> +<test/mot_AS_orario.cpp>
;build_src_filter = -<main.cpp> +<test/mot_PD_orario.cpp>
;build_src_filter = -<main.cpp> +<test/mot_PS_orario.cpp>
;build_src_filter = -<main.cpp> +<test/mot_AD_antiorario.cpp>
;build_src_filter = -<main.cpp> +<test/mot_AS_antiorario.cpp>
;build_src_filter = -<main.cpp> +<test/mot_PD_antiorario.cpp>
;build_src_filter = -<main.cpp> +<test/mot_PS_antiorario.cpp>
;build_src_filter = -<main.cpp> +<test/mot_TUTTI_orario.cpp>
;build_src_filter = -<main.cpp> +<test/mot_all_avanti_indietro.cpp>

lib_deps = adafruit/Adafruit SSD1306@^2.5.16
build_flags = 
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC

monitor_speed = 115200



[env:blackpill_f411ce]
platform = ststm32
board = blackpill_f411ce
framework = arduino
upload_protocol = dfu
lib_deps = ${common.lib_deps} 
monitor_speed = ${common.monitor_speed}

build_flags = 
    ${common.build_flags}
    -D BLACKPILL_F411CE
    

[env:arduino_mega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
lib_deps = ${common.lib_deps} 
monitor_speed = ${common.monitor_speed}
build_src_filter = ${common.build_src_filter}
build_flags = 
    ${common.build_flags}
    -D ARDUINO_MEGA2560

[env:uno]
platform = atmelavr
board = uno
framework = arduino

monitor_speed = 115200
lib_deps = ${common.lib_deps}
build_src_filter = ${common.build_src_filter}

