; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:blackpill_f411ce]
platform = ststm32
board = blackpill_f411ce
framework = arduino
upload_protocol = dfu

monitor_speed = 115200
build_flags = 
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_I2C2
        ; Timer
    -D TIM1_ENABLE
    -D TIM2_ENABLE
    -D TIM3_ENABLE
    -D TIM4_ENABLE
    -D HAL_TIM_MODULE_ENABLED
    
lib_deps = adafruit/Adafruit SSD1306@^2.5.7
;build_src_filter = -<main.cpp> +<test/serial_hw.cpp>
;build_src_filter = -<main.cpp> +<test/blink13.cpp>
;build_src_filter = -<main.cpp> +<test/oled_hw.cpp>
;build_src_filter = -<main.cpp> +<test/scanI2C.cpp>
;build_src_filter = -<main.cpp> +<test/mot_AD_orario.cpp>
;build_src_filter = -<main.cpp> +<test/mot_AS_orario.cpp>
;build_src_filter = -<main.cpp> +<test/mot_PD_orario.cpp>
;build_src_filter = -<main.cpp> +<test/mot_PS_orario.cpp>
;build_src_filter = -<main.cpp> +<test/mot_AD_antiorario.cpp>
;build_src_filter = -<main.cpp> +<test/mot_AS_antiorario.cpp>
;build_src_filter = -<main.cpp> +<test/mot_PD_antiorario.cpp>
;build_src_filter = -<main.cpp> +<test/mot_PS_antiorario.cpp>


build_src_filter = -<main.cpp> +<test/mot_TUTTI_orario.cpp>


;build_src_filter = -<main.cpp> +<test/mot_all_avanti_indietro.cpp>




